### ISSUE TITLE
Greeeeeeed -- I want to make a Donate tab

### ISSUE THREAD

**Issue by joshmadewell** [joshmadewell/optimlol#22]
Users have to click the support tab in the navigation bar in order to even see I have a way to accept donations. I want to have more navigation options so that they are more obvious and maybe that'll lead to $$$

I think:
OptimLoL | FAQ | About | Donate

**Comment by Mike-Dunton** [comment]
Is this resolved with the Donate and Tip buttons you added?

**Comment by joshmadewell** [comment]
yah
