### ISSUE TITLE
Shareable links

### ISSUE THREAD

**Issue by cardona150** [joshmadewell/optimlol#25]
The people want to send a link to their game's optimlol via in-game chat

**Comment by cardona150** [comment]
Parse chat log button hrefs to page with query string (eg http://optimlol.com/?s1=qwer&s2=asdf&s3=zxcv). Not sure what to do in typing case.

**Comment by joshmadewell** [comment]
!!!! this is an awesome awesome awesome idea!!! thanks @cardona150

**Comment by joshmadewell** [comment]
So, the code for this is pretty much complete but I really don't like how long the url is...im looking into signing up for bitly but that's going to involve buying another domain :( might use long urls for the time being

**Comment by joshmadewell** [comment]
We now have shareable links. Thanks again for this suggestion and please let me know what you think about the feature.

**Comment by cardona150** [comment]
When I open a link someone gave me it opens in the region set in my cookies, not necessarily the one they intend me to see. This will only affect players who play in various regions (I last used the site @ LAN and my friend just sent me an "NA" link and there were no results found). Must be passed via link as well (na.optimlol.com, optimlol.com/na/, optimlol.com/?region=na).

**Comment by joshmadewell** [comment]
The region should already be passed through the link, I handled this. I'll
check it out laster today.
