### ISSUE TITLE
Need to add tooltips....

### ISSUE THREAD

**Issue by joshmadewell** [joshmadewell/optimlol#8]
Right now, some of the stuff is really confusing on the page (lane tags are most played in 30 games but some people might thing those are suggestions...). Maybe adding some tool tips would clear up any confusion.

**Comment by Mike-Dunton** [comment]
You should add tool tips to the champions, so that when you hover over them they show the champion's name.

**Comment by joshmadewell** [comment]
Good idea, added and pushed.
